name: API Status Script

on:
  push:
    paths:
    - "**.py"
  schedule:
    - cron: '40 2 * * *'  # This runs the job at 8:10 AM IST (GMT+5:30)
  workflow_dispatch:
jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install git+https://github.com/Vivekkumar-IN/TheApi@${{ github.ref_name }}

      - name: Run API Status Script
        run: |
          python script.py

      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: "Auto Code Formatting Fixes"
            commit_options: "--no-verify"
            repository: .
            commit_user_name: "github-actions[bot]"
            commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
            commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"