name: Upadte Docs

on:
  push:
    paths:
    - "**.py"
    - "**.yml"
  schedule:
    - cron: '40 2 * * *'  # This runs the job at 8:10 AM IST (GMT+5:30)
  workflow_dispatch:
jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          echo "pip install git+https://github.com/Vivekkumar-IN/TheApi@${{ github.ref_name }}"

          pip install git+https://github.com/Vivekkumar-IN/TheApi@${{ github.ref_name }}

      - name: Run API Status Script
        run: |
          python script.py

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git stash
          git pull origin ${{ github.ref_name }}
          git stash pop
          git add README.md
          git commit -m "Update Status of TheApi"
          git push origin ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old workflow run
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          #delete_workflow_pattern: "Upadte Docs"