name: Build docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
          VERSION=v$(python -c "from TheApi import __version__; print(__version__)")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build documentation
        run: |
          cd docs
          make html
          
      - Do or die
         mv build/html/m.html .
         ls 
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/build/html
          single-commit: true
          target-folder: ${{ env.VERSION }}
