name: GitHub Pages

on:
  push:
    branches:
    - dev
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install aiofiles pillow httpx
        pip install sphinx  furo pygments


    - name: Build documentation
      run: |
        cd docs
        make html

    #- name: Deploy to GitHub Pages
    #  uses: peaceiris/actions-gh-pages@v3
     # with:
       # github_token: ${{ secrets.GITHUB_TOKEN }}
       # publish_dir: ./docs/build/html


    - name: Delete old workflow run
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 1

    - name: Deploy to gh-pages branch
      run: |
        find . -mindepth 1 -not -name 'docs' -exec rm -rf {} +
        mv docs/build/html/* .
        rm -rf docs 
        touch .nojekyll
        git init
        git checkout -b gh-pages
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add . -A
        git commit -m "DocGen: Update documentation"
        git push origin gh-pages --force
