name: Build and Deploy Docs

on:
  push:
    branches:
      - dev

jobs:
  setup-and-build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Use the Python version required for your project

      - name: Install Sphinx and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx

      - name: Initialize Sphinx Quickstart
        run: |
          cd docs
          sphinx-quickstart --quiet --project="TheApi" --author="Vivekkumar-in" --release="1.2.7" --ext-autodoc --ext-viewcode --makefile --sep

      - name: List files in docs directory
        run: ls -la docs

      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: "Auto Code Formatting Fixes"
            commit_options: "--no-verify"
            repository: .
            commit_user_name: "github-actions[bot]"
            commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
            commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Upload Sphinx HTML files as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-docs
          path: docs/_build/html/
