name: Build and Deploy Docs

on:
  push:
    branches:
      - dev

jobs:
  setup-and-build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Use the Python version required for your project

      - name: Install Sphinx and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx

      - name: Initialize Sphinx Quickstart
        run: |
          cd docs
          sphinx-quickstart --quiet --project="TheApi" --author="Vivekkumar-in" --release="1.2.7" --ext-autodoc --ext-viewcode --makefile --sep

      - name: List files in docs directory
        run: ls -la docs

      - name: Upload Sphinx HTML files as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-docs
          path: docs/_build/html/
