name: Docs

on:
  push:
    branches:
      - dev

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'


    - name: Build Sphinx Documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: docs/

    - name: Deploy to gh-pages branch
      run: |
        mkdir -p build
        mv _build/html/* build/

        cd build
        git init
        git checkout -b gh-pages
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add .
        git commit --allow-empty -m "Deploy Sphinx documentation"
        git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" gh-pages:gh-pages
